/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package r_m_s;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class v_ticket extends javax.swing.JFrame {

    /**
     * Creates new form v_ticket
     */
    public v_ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket id", "Train Name", "Starting", "Ending", "class", "Fare", "name", "no of passanger", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1350, 290));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Enter ticket id for tickets");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 210, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 690, 90, 80));

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 540, 90, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("View/Delete Ticket");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 360, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Delete Your Ticket Here");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 510, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Enter Your ticket Id-->");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 150, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 110, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Select Class of your ticket  ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 150, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("for security purpose");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 130, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1stAc", "2ndAc", "3rdAc", "Sleepers" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r_m_s/passenger-5593947_1920.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tic_id=jTextField1.getText();
        ResultSet rs=select.getData("select *from ticket where tic_id='"+tic_id+"'");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try{
            while(rs.next())
            {
                model.addRow(new Object[] {rs.getString(1),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(9),rs.getString(10),rs.getString(8)});
            }
            rs.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
setVisible(false);
new u_home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int sa1,sa2,sa3,ss,temp,no_pass,tc;
String clas,train_no,cl;
clas=(String) jComboBox1.getSelectedItem();
String id=jTextField2.getText();
        String Query,Query1;
   ResultSet rs=select.getData("select * from ticket where tic_id='"+id+"'");
       try {
           if(rs.next()){
               cl=rs.getString(6);
                   tc=rs.getInt(1);
                   train_no=rs.getString(2);
                  no_pass=rs.getInt(10);
                  if(clas.equals(rs.getString(6)) & id.equals(rs.getString(1))){
if(rs.getString(6).equals("1stAc")){
    ResultSet rd=select.getData("select * from train where train_no='"+train_no+"'");
       try {
           if(rd.next()){
               
                   sa1 = rd.getInt(5);
                   
    temp = sa1 + no_pass;
    
        Query="Delete from ticket where tic_id='"+id+"'";
    insertupdatedelete.setData(Query,"");
    Query1="update train set sia1="+temp+" where train_no='"+train_no+"'";
    insertupdatedelete.setData(Query1,"Deleted Successfull !");
    setVisible(false);
    new v_ticket().setVisible(true);}}
    catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e);
       }
    }
else if(rs.getString(6).equals("2ndAc")){
    ResultSet rd=select.getData("select * from train where train_no='"+train_no+"'");
       try {
           if(rd.next()){
               
                   sa2 = rd.getInt(6);
                   temp = sa2 + no_pass;
    
        Query="Delete from ticket where tic_id='"+id+"'";
    insertupdatedelete.setData(Query,"");
    Query1="update train set sia2="+temp+" where train_no='"+train_no+"'";
    insertupdatedelete.setData(Query1,"Deleted Successfull !");
    setVisible(false);
    new v_ticket().setVisible(true);}}
    catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e);
       }
}
else if(rs.getString(6).equals("3rdAc")){
ResultSet rd=select.getData("select * from train where train_no='"+train_no+"'");
       try {
           if(rd.next()){
               
                   sa3 = rd.getInt(7);
                  temp = sa3 + no_pass;
    
        Query="Delete from ticket where tic_id='"+id+"'";
    insertupdatedelete.setData(Query,"");
    Query1="update train set sia3="+temp+" where train_no='"+train_no+"'";
    insertupdatedelete.setData(Query1,"Deleted Successfull !");
    setVisible(false);
    new v_ticket().setVisible(true);}}
    catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e);
       }    
}
else if(rs.getString(6).equals("Sleepers")){
       ResultSet rd=select.getData("select * from train where train_no='"+train_no+"'");
       try {
           if(rd.next()){
               
                   ss = rd.getInt(8);
    temp = ss + no_pass;
    
        Query="Delete from ticket where tic_id='"+id+"'";
    insertupdatedelete.setData(Query,"");
    Query1="update train set sis="+temp+" where train_no='"+train_no+"'";
    insertupdatedelete.setData(Query1,"Deleted Successfull !");
    setVisible(false);
    new v_ticket().setVisible(true);}}
    catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e);
       }
     }}else{JOptionPane.showMessageDialog(null,"Incorrect Id or you select a wrong class");}
           }}         
        catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e);
       }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
